### PR TITLE
Get the number of syslog clients

### PR DESCRIPTION
**Pull request by ktsakalozos**

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Reporting the syslog connections is used by: https://github.com/juju-solutions/layer-apache-flume-syslog/pull/5

**Comment by johnsca** [comment]
LGTM

**Comment by kwmonroe** [comment]
Sorry I was late to the party, but I would prefer nodes() be called client_count().  The former doesn't tell me what a node is, and worse, it makes me think I'm getting some structure with all the connected clients (vs just the len() of that struct).

**Comment by ktsakalozos** [comment]
Agreed, client_count() looks much better, thank you. See, PR: https://github.com/juju-solutions/interface-syslog/pull/6

**Pull request merged**
